name: Build OrangeFox Recovery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout device tree
        run: |
          git clone --depth=1 https://github.com/Myron-Forge/device_xiaomi_myron.git device/xiaomi/myron
        shell: bash

      - name: Install repo
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq repo
          which repo && repo version
        shell: bash

      - name: Checkout OrangeFox source
        run: |
          mkdir -p ~/work
          cd ~/work
          git config --global credential.helper store
          repo init -u https://github.com/OrangeFoxRecovery/fox-6.0_manifest -b fox_6.0 --depth=1
          repo sync -c -j8 --no-tags
        shell: bash

      - name: Setup and build
        run: |
          cd ~/work
          source build/envsetup.sh
          export DEVICE=myron
          export OEM=xiaomi
          export OF_MAINTAINER=KouJunHao
          export LC_ALL=C
          export FOX_USE_LATEST_MAGISK=true
          export USE_CCACHE=1
          lunch omni_myron-eng
          mka -j8 recoveryimage
        shell: bash

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-myron
          path: ~/work/out/target/product/myron/OrangeFox*.zip
          retention-days: 5
